#ifndef _COLOR_H_
#define _COLOR_H_

#define BRIGHT_RED FOREGROUND_RED|FOREGROUND_INTENSITY
#define BRIGHT_GREEN FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define BRIGHT_BLUE FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define BRIGHT_YELLOW FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_INTENSITY
#define BRIGHT_MAGENTA FOREGROUND_RED|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define BRIGHT_CYAN FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define BRIGHT_WHITE FOREGROUND_RED|FOREGROUND_GREEN|FOREGROUND_BLUE|FOREGROUND_INTENSITY
#define MAGENTA FOREGROUND_RED|FOREGROUND_BLUE

/*p_op - Process Operation*/
void setColor(WORD wColor);

#endif
